import random
import time
print('hell0o world')
print()
print('What is your name?')
yourName = input()
print('Your name is ' + str(yourName))
print()
print('What is your favorit color?')
favColor = input()
print('Your favorit color is ' + favColor)
print('give a number')
num1 = input() # random.randint(1,10)
print('give a number')
num2 = input() # random.randint(1,10)
print (num1+ '+' + num2 + '=' + str(float(num1) + float(num2)))
print(num1 + '-' + num2 +'=' + str(float(num1) - float(num2)))
print(num1 + '/' + num2 +'=' + str(float(num1) / float(num2)))
print(num1 + '*' + num2 +'=' + str(float(num1) * float(num2)))
print()
time.sleep(.1)
num3 = random.randint(1,10)
num4 = random.randint(1,10)
print('I want to')
print(num3)
print(num4)
print(num3 + num4)
print(num3 - num4)
print(num3 * num4)
print(num3 / num4)
