print('What do you get when you cross snowman with a vampire?')
input()
print('Frostbite')
print()
print('What do you call and astronaut\'s cavvity')
input()
print('A black hole')
print('Knock knock.')
input()
print("Who's there?")
input()
print('Interrupting cow')
input()
print('Interrupting cow wh', end= '')
print('-MOO!')
